[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "clearsight-ml"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
dependencies = [
  "boto3==1.35.99",
  "fastapi==0.115.6",
  "huggingface-hub==0.27.1",
  "httpx==0.28.1",
  "numpy==1.26.4",
  "opencv-python-headless==4.10.0.84",
  "prometheus-client==0.21.1",
  "pydantic==2.10.4",
  "redis==5.2.1",
  "segmentation-models==0.5.0",
  "tensorflow==2.16.1",
  "timm==1.0.7",
  "torch==2.7.0",
  "torchvision==0.22.0",
  "uvicorn[standard]==0.34.0"
]

[project.optional-dependencies]
dev = [
  "mypy==1.14.1",
  "pytest==8.3.4",
  "ruff==0.9.2",
  "types-redis==4.6.0.20241004"
]

[tool.setuptools.packages.find]
where = [".."]
include = ["ml*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [".."]

[tool.ruff]
target-version = "py310"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
  "ml.inference.cdr",
  "ml.inference.postprocessing",
  "ml.tests.test_cdr"
]
ignore_errors = true
